name: Tests

on:
  push:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  STABLE_PYTHON_VERSION: "3.11"

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and dependencies with uv
        run: |
          uv pip install --system -e ".[test]"
          uv pip install --system nbmake ipykernel

      - name: Run linting (continues on error)
        if: matrix.python-version == env.STABLE_PYTHON_VERSION && runner.os == 'Linux'
        continue-on-error: true 
        run: |
          uv run ruff check .  --output-format=text > ruff-lint-report.txt || true
          cat ruff-lint-report.txt

      - name: Upload Ruff lint report
        if: matrix.python-version == env.STABLE_PYTHON_VERSION && runner.os == 'Linux'
        uses: actions/upload-artifact@v7
        with:
          name: ruff-lint-report
          path: ruff-lint-report.txt
          retention-days: 30

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=castor_etc --cov-report=xml --cov-report=html --cov-report=term-missing tests/

      - name: Generate Coverage Summary
        # Use GHA logic instead of shell logic to handle cross-platform compatibility
        if: runner.os == 'Linux' && matrix.python-version == '3.11'
        run: |
          echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage HTML report
        if: matrix.python-version == env.STABLE_PYTHON_VERSION && runner.os == 'Linux'
        uses: actions/upload-artifact@v7
        with:
          name: coverage-html-report
          path: |
            htmlcov/
            ruff-lint-report.txt
            coverage.xml
          retention-days: 30

  # # Validate the example notebooks using nbmake
  # notebooks:
  #   name: Notebooks (Linux)
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #       with:
  #         submodules: true
  #     - uses: astral-sh/setup-uv@v7
  #     - name: Run nbmake
  #       run: |
  #         uv pip install --system -e .
  #         uv pip install --system nbmake ipykernel
  #         uv run pytest --nbmake examples/notebooks/ETC_notebooks/