name: Tests for all branch pushes

on:
    push:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os == 'macos-latest' && 'macOS' || matrix.os == 'windows-latest' && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Lint
        if: matrix.python-version == '3.9' && runner.os == 'Linux'
        run: hatch run lint:all

      - name: Run tests and track code coverage
        run: hatch run cov